version: '3.9'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"

  mysql-auth:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
