server:
  port: 9191

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: NFT-SERVICE
          uri: lb://NFT-SERVICE
          predicates:
            - Path=/api/nfts/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://auth-service/.well-known/jwks.json