server:
  port: 9191  # Cổng riêng của gateway, không đụng với Eureka

spring:
  application:
    name: cloud-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: NFT-SERVICE
          uri: lb://NFT-SERVICE
          predicates:
            - Path=/api/v1/nft/**
          filters:
            - StripPrefix=3

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3
        - id: AI-SERVICE
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - StripPrefix=3
    discovery:
      enabled: true
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Đảm bảo eureka-server đang chạy ở đây
    register-with-eureka: true
    fetch-registry: true