<<<<<<< HEAD
spring:
  application:
    name: nft-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
=======
server:
  port: 8083

spring:
  application:
    name: nft-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
>>>>>>> 521b5ee (refactor(docker) combine sevices to 1 register)
